name: eg-move-project

services:
  eg-move:
    image: jmebrohart/egmove:latest
    container_name: eg-move
    restart: unless-stopped
    ports:
      - "8080:8000"
    volumes:
      - ./data:/app/data
    environment:
      - MAX_UPLOAD_SIZE=0
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
    networks:
      - proxy_net

networks:
  proxy_net:
    name: proxy_net  
    driver: bridge   