services:
  eg-move:
    build: .
    container_name: eg-move
    restart: unless-stopped
    ports:
      - "8080:8000"  # Host Port : Container Port
    volumes:
      - ./data:/app/data  # Persist uploaded files
    environment:
      - MAX_UPLOAD_SIZE=0 # Application specific config
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true # Connect to existing proxy network
